const SHOP_DATA = {
  "games": [
    {
      "id": "unturned",
      "name": "Unturned",
      "icon": "fa-solid fa-gun",
      "categories": [
        "All Items",
        "Ammunition Box",
        "Barricade",
        "Clothes",
        "Dingus",
        "Food",
        "Gas",
        "Material",
        "Medical",
        "Miscellaneous",
        "Parachute",
        "Spraycans",
        "Supplies",
        "Tobacco",
        "Tools",
        "Weapons"
      ],
      "vehicleCategories": [
        "All Vehicles",
        "Vanilla",
        "Unite Vehicles",
        "Vanilla Vehicles Legacy",
        {"name": "Death's Gaming Vehicles", "comingSoon": true }
      ],
      "items": [

        /* ── AMMUNITION BOX ── Vanilla ── */
        { "name": "Low Caliber Military Ammunition Crate",  "id": "43",   "price": "400",  "sell": "0", "category": "Ammunition Box", "subCategory": "Vanilla",                       "available": true },
        { "name": "Low Caliber Civilian Ammunition Box",    "id": "44",   "price": "250",  "sell": "0", "category": "Ammunition Box", "subCategory": "Vanilla",                       "available": true },
        { "name": "Low Caliber Ranger Ammunition Box",      "id": "119",  "price": "400",  "sell": "0", "category": "Ammunition Box", "subCategory": "Vanilla",                       "available": true },
        { "name": "High Caliber Military Ammunition Crate", "id": "1192", "price": "750",  "sell": "0", "category": "Ammunition Box", "subCategory": "Vanilla",                       "available": true },
        { "name": "High Caliber Ranger Ammunition Box",     "id": "1193", "price": "750",  "sell": "0", "category": "Ammunition Box", "subCategory": "Vanilla",                       "available": true },

        /* ── AMMUNITION BOX ── Modern Weapon Armory ── */
        { "name": "4.6x30mm Action SX",          "id": "35014", "price": "1400",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "4.73x33mm DM11",              "id": "36237", "price": "2000",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "4.85x49mm XL1",               "id": "36239", "price": "1500",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "5.45x39mm M74 FMJ",           "id": "35024", "price": "3500",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "5.56x30mm MARS Wildcat",      "id": "36692", "price": "1200",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "5.56x45mm NATO Warmagedon",   "id": "35020", "price": "2500",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "5.7x28mm SS190",              "id": "35016", "price": "1800",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "5.8x42mm DAP87",              "id": "35056", "price": "1200",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "6.8x51mm Fury",               "id": "36241", "price": "1200",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "7.62x25mm TT FMJ43",          "id": "35006", "price": "1000",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "7.92x33mm Kurz FMJ",          "id": "36235", "price": "2000",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "7.62x39mm M43 BP gzh",        "id": "35022", "price": "1800",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "7.62x51mm NATO M80",          "id": "35032", "price": "3500",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "7.62x54mmR LPS gzh",          "id": "35034", "price": "2700",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "7.7x58mm Arisaka FMJ",        "id": "36952", "price": "1100",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "7.92x57mm Mauser FMJ",        "id": "36233", "price": "3500",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "8x22mm Nambu FMJ",            "id": "36954", "price": "900",   "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "9x18mm PM PBM gzh",           "id": "35004", "price": "800",   "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "9x19mm RIP",                  "id": "35002", "price": "1100",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "9x21mm Gyruza BT gzh",        "id": "35012", "price": "750",   "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "9x39mm SP-6",                 "id": "35026", "price": "950",   "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "9.3x64mm Brenneke 7N33",      "id": "35038", "price": "1400",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "10x21mm Auto FMJ",            "id": "36378", "price": "1500",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "12.7x55mm STs-130 PS12B",     "id": "35028", "price": "3000",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "12.7x108mm BZT-44M",          "id": "36386", "price": "5000",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "14.5x114mm AP",               "id": "36243", "price": "8000",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "12 Gauge Buckshot",           "id": "35046", "price": "700",   "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "12 Gauge AP-20 Slug",         "id": "35048", "price": "1200",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "12 Gauge FRAG-12",            "id": "35050", "price": "1500",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "20 Gauge Buckshot",           "id": "35044", "price": "500",   "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "23x75mm Shrapnel-25",         "id": "35052", "price": "700",   "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "23x75mm Barrikada",           "id": "35054", "price": "700",   "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": "23x75mm Zvezda",              "id": "36388", "price": "700",   "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": ".22 LR HP",                   "id": "36382", "price": "650",   "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": ".300BLK M62",                 "id": "36690", "price": "2400",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": ".300 Winchester Magnum AP",   "id": "36626", "price": "2000",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": ".30-06 M2",                   "id": "36950", "price": "1600",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": ".303British FMJ",             "id": "35042", "price": "1500",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": ".336 TKM AP",                 "id": "35018", "price": "1900",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": ".338 Lapua Magnum AP",        "id": "35040", "price": "3000",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": ".338 Norma Magnum AP",        "id": "36384", "price": "3100",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": ".357 Magnum FMJ",             "id": "36380", "price": "800",   "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": ".408CheyTac T-50",            "id": "35036", "price": "3500",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": ".410 Gauge Buckshot",         "id": "36506", "price": "1500",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": ".44 Magnum JHP",              "id": "35008", "price": "800",   "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": ".45 ACP AP",                  "id": "35010", "price": "1200",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": ".45LC LP",                    "id": "36504", "price": "1000",  "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": ".455 Webley JHP",             "id": "36956", "price": "800",   "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },
        { "name": ".50 BMG FMJ",                 "id": "35030", "price": "10000", "sell": "0", "category": "Ammunition Box", "subCategory": "Modern Weapon Armory", "available": true },

        /* ── BARRICADE ── Other Mods ── */
        { "name": "License Plate", "id": "17109", "price": "10",    "sell": "0",    "category": "Barricade", "subCategory": "Other Mods", "available": true },
        { "name": "Admin Locker",  "id": "52555", "price": "15000", "sell": "5000", "category": "Barricade", "subCategory": "Other Mods", "available": true },
        { "name": "Wall Locker",   "id": "20354", "price": "1500",  "sell": "0",    "category": "Barricade", "subCategory": "Other Mods", "available": true },
        { "name": "Safe",          "id": "20352", "price": "1200",  "sell": "0",    "category": "Barricade", "subCategory": "Other Mods", "available": true },
        { "name": "Garden Locker", "id": "20353", "price": "1000",  "sell": "0",    "category": "Barricade", "subCategory": "Other Mods", "available": true },
        { "name": "Chest",         "id": "20351", "price": "1000",  "sell": "0",    "category": "Barricade", "subCategory": "Other Mods", "available": true },
        { "name": "Small Safe",    "id": "20350", "price": "800",   "sell": "0",    "category": "Barricade", "subCategory": "Other Mods", "available": true },

        /* ── CLOTHES ── Vanilla ── */
        { "name": "Alicepack", "id": "253", "price": "5000", "sell": "0", "category": "Clothes", "subCategory": "Vanilla", "available": true },

        /* ── CLOTHES ── Other Mods ── */
        { "name": "Toxicity Godlike Freighter Pack", "id": "7648", "price": "610000", "sell": "0", "category": "Clothes", "subCategory": "Other Mods", "available": true },

        /* ── DINGUS ── */
        { "name": "Dingus", "id": "63620", "price": "100", "sell": "0", "category": "Dingus", "subCategory": "Other Mods", "available": true },

        /* ── FOOD ── Vanilla ── */
        { "name": "Canned Beans",  "id": "13",   "price": "15",  "sell": "0",  "category": "Food", "subCategory": "Vanilla", "available": true },
        { "name": "Bottled Water", "id": "14",   "price": "15",  "sell": "0",  "category": "Food", "subCategory": "Vanilla", "available": true },
        { "name": "MRE",           "id": "81",   "price": "200", "sell": "0",  "category": "Food", "subCategory": "Vanilla", "available": true },
        { "name": "Raw Trout",     "id": "504",  "price": "100", "sell": "50", "category": "Food", "subCategory": "Vanilla", "available": true },
        { "name": "Raw Salmon",    "id": "505",  "price": "80",  "sell": "40", "category": "Food", "subCategory": "Vanilla", "available": true },
        { "name": "Raw Minnow",    "id": "1347", "price": "70",  "sell": "35", "category": "Food", "subCategory": "Vanilla", "available": true },
        { "name": "Raw Goldfish",  "id": "1349", "price": "60",  "sell": "30", "category": "Food", "subCategory": "Vanilla", "available": true },
        { "name": "Raw Bass",      "id": "1351", "price": "110", "sell": "55", "category": "Food", "subCategory": "Vanilla", "available": true },
        { "name": "Raw Squid",     "id": "1434", "price": "140", "sell": "70", "category": "Food", "subCategory": "Vanilla", "available": true },

        /* ── FOOD ── More Farming Mod ── */
        { "name": "Raw Carp",     "id": "43105", "price": "40",  "sell": "40",  "category": "Food", "subCategory": "More Farming Mod", "available": true },
        { "name": "Raw Shrimp",   "id": "43107", "price": "30",  "sell": "30",  "category": "Food", "subCategory": "More Farming Mod", "available": true },
        { "name": "Raw Sardine",  "id": "43109", "price": "40",  "sell": "40",  "category": "Food", "subCategory": "More Farming Mod", "available": true },
        { "name": "Raw King Crab","id": "43115", "price": "100", "sell": "100", "category": "Food", "subCategory": "More Farming Mod", "available": true },
        { "name": "Raw Eel",      "id": "43117", "price": "55",  "sell": "55",  "category": "Food", "subCategory": "More Farming Mod", "available": true },

        /* ── GAS ── */
        { "name": "Portable Gas Can", "id": "28", "price": "500", "sell": "0", "category": "Gas", "subCategory": "Vanilla", "available": true },

        /* ── MATERIAL ── Vanilla ── */
        { "name": "Birch Log",      "id": "37",  "price": "12",  "sell": "2", "category": "Material", "subCategory": "Vanilla", "available": true },
        { "name": "Birch Stick",    "id": "38",  "price": "2",   "sell": "1", "category": "Material", "subCategory": "Vanilla", "available": true },
        { "name": "Maple Log",      "id": "39",  "price": "12",  "sell": "2", "category": "Material", "subCategory": "Vanilla", "available": true },
        { "name": "Maple Stick",    "id": "40",  "price": "2",   "sell": "1", "category": "Material", "subCategory": "Vanilla", "available": true },
        { "name": "Pine Log",       "id": "41",  "price": "12",  "sell": "2", "category": "Material", "subCategory": "Vanilla", "available": true },
        { "name": "Pine Stick",     "id": "42",  "price": "2",   "sell": "1", "category": "Material", "subCategory": "Vanilla", "available": true },
        { "name": "Rope",           "id": "64",  "price": "42",  "sell": "0", "category": "Material", "subCategory": "Vanilla", "available": true },
        { "name": "Wire",           "id": "65",  "price": "35",  "sell": "0", "category": "Material", "subCategory": "Vanilla", "available": true },
        { "name": "Cloth",          "id": "66",  "price": "10",  "sell": "4", "category": "Material", "subCategory": "Vanilla", "available": true },
        { "name": "Metal Scrap",    "id": "67",  "price": "15",  "sell": "4", "category": "Material", "subCategory": "Vanilla", "available": true },
        { "name": "Metal Sheet",    "id": "68",  "price": "60",  "sell": "0", "category": "Material", "subCategory": "Vanilla", "available": true },
        { "name": "Tape",           "id": "69",  "price": "16",  "sell": "0", "category": "Material", "subCategory": "Vanilla", "available": true },
        { "name": "Nails",          "id": "71",  "price": "60",  "sell": "0", "category": "Material", "subCategory": "Vanilla", "available": true },
        { "name": "Metal Can",      "id": "72",  "price": "60",  "sell": "0", "category": "Material", "subCategory": "Vanilla", "available": true },
        { "name": "Raw Explosives", "id": "73",  "price": "125", "sell": "9", "category": "Material", "subCategory": "Vanilla", "available": true },
        { "name": "Bricks",         "id": "74",  "price": "20",  "sell": "0", "category": "Material", "subCategory": "Vanilla", "available": true },
        { "name": "Chemicals",      "id": "75",  "price": "250", "sell": "0", "category": "Material", "subCategory": "Vanilla", "available": true },
        { "name": "Metal Bar",      "id": "285", "price": "8",   "sell": "0", "category": "Material", "subCategory": "Vanilla", "available": true },
        { "name": "Leather",        "id": "516", "price": "20",  "sell": "6", "category": "Material", "subCategory": "Vanilla", "available": true },

        /* ── MATERIAL ── Other Mods ── */
        { "name": "Gun Powder",    "id": "14252", "price": "20",  "sell": "0",  "category": "Material", "subCategory": "Other Mods", "available": true },
        { "name": "Charm",         "id": "39503", "price": "300", "sell": "25", "category": "Material", "subCategory": "Other Mods", "available": true },
        { "name": "Standard Coin", "id": "62626", "price": "500", "sell": "75", "category": "Material", "subCategory": "Other Mods", "available": true },

        /* ── MEDICAL ── */
        { "name": "Medkit", "id": "15", "price": "125", "sell": "0", "category": "Medical", "subCategory": "Vanilla", "available": true },

        /* ── MISCELLANEOUS ── */
        { "name": "$100 Note", "id": "1055", "price": "200", "sell": "0", "category": "Miscellaneous", "subCategory": "Vanilla", "available": true },

        /* ── PARACHUTE ── */
        { "name": "Umbrella", "id": "1103 • 1122 → 1128", "price": "200", "sell": "0", "category": "Parachute", "subCategory": "Vanilla", "available": true },

        /* ── SPRAYCANS ── Unite Spraycans ── */
        { "name": "Black Spraycan",     "id": "40000", "price": "50", "sell": "0", "category": "Spraycans", "subCategory": "Unite Spraycans", "available": true },
        { "name": "Blue Spraycan",      "id": "40001", "price": "50", "sell": "0", "category": "Spraycans", "subCategory": "Unite Spraycans", "available": true },
        { "name": "Dark Grey Spraycan", "id": "40002", "price": "50", "sell": "0", "category": "Spraycans", "subCategory": "Unite Spraycans", "available": true },
        { "name": "Grey Spraycan",      "id": "40003", "price": "50", "sell": "0", "category": "Spraycans", "subCategory": "Unite Spraycans", "available": true },
        { "name": "Green Spraycan",     "id": "40004", "price": "50", "sell": "0", "category": "Spraycans", "subCategory": "Unite Spraycans", "available": true },
        { "name": "Orange Spraycan",    "id": "40005", "price": "50", "sell": "0", "category": "Spraycans", "subCategory": "Unite Spraycans", "available": true },
        { "name": "Purple Spraycan",    "id": "40006", "price": "50", "sell": "0", "category": "Spraycans", "subCategory": "Unite Spraycans", "available": true },
        { "name": "Red Spraycan",       "id": "40007", "price": "50", "sell": "0", "category": "Spraycans", "subCategory": "Unite Spraycans", "available": true },
        { "name": "White Spraycan",     "id": "40008", "price": "50", "sell": "0", "category": "Spraycans", "subCategory": "Unite Spraycans", "available": true },
        { "name": "Yellow Spraycan",    "id": "40009", "price": "50", "sell": "0", "category": "Spraycans", "subCategory": "Unite Spraycans", "available": true },

        /* ── SUPPLIES ── Sir Vuval's Advanced Structures ── */
        { "name": "Limestones",     "id": "49400", "price": "10", "sell": "0", "category": "Supplies", "subCategory": "Sir Vuval's Advanced Structures", "available": true },
        { "name": "Lump o' Clay",   "id": "49401", "price": "10", "sell": "0", "category": "Supplies", "subCategory": "Sir Vuval's Advanced Structures", "available": true },
        { "name": "Sack o' Silt",   "id": "49402", "price": "50", "sell": "0", "category": "Supplies", "subCategory": "Sir Vuval's Advanced Structures", "available": true },
        { "name": "Red Shingles",   "id": "49403", "price": "10", "sell": "0", "category": "Supplies", "subCategory": "Sir Vuval's Advanced Structures", "available": true },
        { "name": "Grey Shingles",  "id": "49404", "price": "10", "sell": "0", "category": "Supplies", "subCategory": "Sir Vuval's Advanced Structures", "available": true },
        { "name": "Paintcan (Red)", "id": "49405", "price": "50", "sell": "0", "category": "Supplies", "subCategory": "Sir Vuval's Advanced Structures", "available": true },
        { "name": "Paintcan (Grey)","id": "49406", "price": "50", "sell": "0", "category": "Supplies", "subCategory": "Sir Vuval's Advanced Structures", "available": true },
        { "name": "Stonebricks",    "id": "49410", "price": "50", "sell": "0", "category": "Supplies", "subCategory": "Sir Vuval's Advanced Structures", "available": true },
        { "name": "Rocks",          "id": "49412", "price": "10", "sell": "0", "category": "Supplies", "subCategory": "Sir Vuval's Advanced Structures", "available": true },
        { "name": "Pine Timber",    "id": "49414", "price": "50", "sell": "0", "category": "Supplies", "subCategory": "Sir Vuval's Advanced Structures", "available": true },
        { "name": "Coal",           "id": "49416", "price": "10", "sell": "0", "category": "Supplies", "subCategory": "Sir Vuval's Advanced Structures", "available": true },
        { "name": "Iron Ore",       "id": "49418", "price": "30", "sell": "0", "category": "Supplies", "subCategory": "Sir Vuval's Advanced Structures", "available": true },
        { "name": "Iron Fittings",  "id": "49424", "price": "50", "sell": "0", "category": "Supplies", "subCategory": "Sir Vuval's Advanced Structures", "available": true },

        /* ── TOBACCO ── Animated Cigarettes & Cigars ── */
        { "name": "Tobacco Seed",   "id": "26412", "price": "500", "sell": "2",  "category": "Tobacco", "subCategory": "Animated Cigarettes & Cigars", "available": true },
        { "name": "Homemade Cigar", "id": "26411", "price": "100", "sell": "25", "category": "Tobacco", "subCategory": "Animated Cigarettes & Cigars", "available": true },
        { "name": "Single Cigarette","id": "26409", "price": "75",  "sell": "15", "category": "Tobacco", "subCategory": "Animated Cigarettes & Cigars", "available": true },

        /* ── TOOLS ── Vanilla ── */
        { "name": "Blowtorch",   "id": "76",   "price": "175",  "sell": "10",  "category": "Tools", "subCategory": "Vanilla", "available": true },
        { "name": "Pickaxe",     "id": "1198", "price": "350",  "sell": "0",   "category": "Tools", "subCategory": "Vanilla", "available": true },
        { "name": "Jackhammer",  "id": "1475", "price": "700",  "sell": "0",   "category": "Tools", "subCategory": "Vanilla", "available": true },
        { "name": "Detonator",   "id": "1240", "price": "3000", "sell": "300", "category": "Tools", "subCategory": "Vanilla", "available": true },
        { "name": "Filter",      "id": "1271", "price": "400",  "sell": "0",   "category": "Tools", "subCategory": "Vanilla", "available": true },

        /* ── TOOLS ── Creator Tools ── */
        { "name": "Transparent Display Wall Sign",  "id": "48473", "price": "50", "sell": "0", "category": "Tools", "subCategory": "Creator Tools", "available": true },
        { "name": "Transparent Item Display",       "id": "48469", "price": "50", "sell": "0", "category": "Tools", "subCategory": "Creator Tools", "available": true },
        { "name": "Transparent Item Wall Display",  "id": "48474", "price": "50", "sell": "0", "category": "Tools", "subCategory": "Creator Tools", "available": true },
        { "name": "Transparent Display Visualizer", "id": "48470", "price": "10", "sell": "0", "category": "Tools", "subCategory": "Creator Tools", "available": true },

        /* ── TOOLS ── Other Mods ── */
        { "name": "Pento Sewing Kit", "id": "34108", "price": "450", "sell": "0",  "category": "Tools", "subCategory": "Other Mods", "available": false },
        { "name": "Sewing Kit",       "id": "62526", "price": "100", "sell": "50", "category": "Tools", "subCategory": "Other Mods", "available": true  },

        /* ── WEAPONS ── Vanilla ── */
        { "name": "Kitchen Knife", "id": "120", "price": "125", "sell": "0", "category": "Weapons", "subCategory": "Vanilla", "available": true },

        /* ═══════════════════════════ VEHICLES ═══════════════════════════ */

        /* ── Vanilla vehicles ── */
        { "name": "Vodyanov",    "id": "119", "price": "7500",  "sell": "0", "category": "Vanilla", "subCategory": "Military", "available": true },
        { "name": "Hummingbird", "id": "107", "price": "7500",  "sell": "0", "category": "Vanilla", "subCategory": "Air",      "available": true },
        { "name": "Police Launch","id": "108", "price": "9000",  "sell": "0", "category": "Vanilla", "subCategory": "Boat",     "available": true },
        { "name": "Dinghy",      "id": "124", "price": "7500",  "sell": "0", "category": "Vanilla", "subCategory": "Boat",     "available": true },
        { "name": "Fighter Jet", "id": "140", "price": "15000", "sell": "0", "category": "Vanilla", "subCategory": "Air",      "available": true },

        /* ── Unite Vehicles ── Civilian ── */
        { "name": "Abarth 500",                    "id": "50022", "price": "20000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Acura NSX 2016",                "id": "50035", "price": "110000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Acura NSX 2016 (Tuning)",       "id": "50036", "price": "150000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Alfa Romeo 4C",                 "id": "50049", "price": "68000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Aston Martin DB5",              "id": "50028", "price": "35000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Audi RS6 Avant",                "id": "50033", "price": "60000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Audi S5",                       "id": "50010", "price": "40000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "BMW Z8",                        "id": "50031", "price": "70000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Chevrolet Camaro SS 1967",      "id": "50007", "price": "28000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Chevrolet Camaro Z28",          "id": "50037", "price": "90000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Chevrolet Corvette C5",         "id": "50011", "price": "55000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Chevrolet Corvette C7 ZR1",     "id": "50014", "price": "105000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Dodge Challenger RT 1971",      "id": "50002", "price": "19000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Dodge Charger LD",              "id": "50048", "price": "50000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Dodge Charger R/T",             "id": "50041", "price": "19000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Dodge Viper GTS 1999",          "id": "50034", "price": "130000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Ferrari F430 Scuderia",         "id": "50038", "price": "150000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Ferrari LaFerrari",             "id": "50020", "price": "180000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Ford F-150 XLT",               "id": "50023", "price": "30000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Ford GT (Gen 2)",               "id": "49011", "price": "110000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Ford GT (Gen 2) Heritage",      "id": "50055", "price": "115000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Ford Mustang Fastback 1967",    "id": "50027", "price": "28000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Ford Mustang GT 2015",          "id": "50017", "price": "80000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Honda Integra Type R",          "id": "50043", "price": "25000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Jaguar F-Type R",              "id": "49012", "price": "78000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Koenigsegg CCX",               "id": "49013", "price": "192000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Lexus LFA",                    "id": "49014", "price": "105000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Marussia B2",                  "id": "50016", "price": "140000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Mazda MX5 ND",                 "id": "50025", "price": "40000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Mazda MX5 ND (Tuning)",        "id": "50026", "price": "50000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Mercedes C63 AMG Black Series","id": "49015", "price": "130000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Mercedes SLS AMG",             "id": "50013", "price": "85000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Mitsubishi Lancer EVO 6",      "id": "50008", "price": "40000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Mitsubishi Lancer EVO 6 (Rally)","id":"50009","price": "42000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Nissan 200SX",                 "id": "50003", "price": "24000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Nissan 200SX (Tuning)",        "id": "50004", "price": "34000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Nissan 240SX",                 "id": "50039", "price": "21000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Nissan 240SX (Tuning)",        "id": "50040", "price": "48000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Nissan 370Z Nismo",            "id": "50032", "price": "100000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Nissan GTR R35 2007",          "id": "50015", "price": "135000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Nissan R390 GT1",              "id": "50018", "price": "200000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Nissan R390 GT1 (Calsonic)",   "id": "50019", "price": "210000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Nissan Safari Turbo",          "id": "50024", "price": "18000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Nissan Silvia S15",            "id": "50046", "price": "35000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Nissan Silvia S15 (Tuning)",   "id": "50047", "price": "40000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Nissan Skyline R31 GT-S",      "id": "50029", "price": "31000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Nissan Skyline R34 GT-R Nismo Z-Tune","id":"49016","price":"120000","sell":"0","category":"Unite Vehicles","subCategory":"Civilian","available":true},
        { "name": "Nissan Z",                     "id": "50012", "price": "125000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Nissan Z (Tuning)",            "id": "50030", "price": "60000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Peugeot 206 GTi",              "id": "50044", "price": "18000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Plymouth Hemi 'Cuda",          "id": "50045", "price": "27000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Saleen S7 TT",                 "id": "50021", "price": "190000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Shelby AC Cobra",              "id": "49017", "price": "85000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Smart FourTwo",                "id": "50042", "price": "15000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Toyota Corolla GTS",           "id": "50000", "price": "20000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Toyota Corolla GTS (Tuning)",  "id": "50005", "price": "33000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Volkswagen Golf GTI Mk1",      "id": "50001", "price": "17000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Volkswagen Golf GTI Mk4",      "id": "50006", "price": "24000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Bus",                          "id": "49999", "price": "40000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },
        { "name": "Firetruck",                    "id": "49998", "price": "35000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Civilian", "available": true },

        /* ── Unite Vehicles ── Police ── */
        { "name": "Acura NSX 2016 (Police)",              "id": "49018", "price": "120000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Police", "available": true },
        { "name": "Acura NSX 2016 (Undercover)",          "id": "49019", "price": "125000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Police", "available": true },
        { "name": "Chevrolet Corvette C7 ZR1 (Police)",   "id": "49020", "price": "115000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Police", "available": true },
        { "name": "Chevrolet Corvette C7 ZR1 (Undercover)","id":"49021", "price": "120000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Police", "available": true },
        { "name": "Dodge Charger LD (Police)",            "id": "49006", "price": "55000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Police", "available": true },
        { "name": "Dodge Charger LD (Undercover)",        "id": "49022", "price": "60000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Police", "available": true },
        { "name": "Ford GT (Gen 2 Police)",               "id": "49007", "price": "115000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Police", "available": true },
        { "name": "Ford GT (Gen 2 Undercover)",           "id": "49008", "price": "120000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Police", "available": true },
        { "name": "Ford Mustang GT 2015 (Police)",        "id": "49004", "price": "90000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Police", "available": true },
        { "name": "Ford Mustang GT 2015 (Undercover)",    "id": "49023", "price": "95000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Police", "available": true },
        { "name": "Marussia B2 (Police)",                 "id": "49000", "price": "150000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Police", "available": true },
        { "name": "Marussia B2 (Undercover)",             "id": "49001", "price": "165000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Police", "available": true },
        { "name": "Mercedes C63 AMG Black Series (Police)","id":"49009", "price": "135000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Police", "available": true },
        { "name": "Mercedes C63 AMG Black Series (Undercover)","id":"49010","price":"140000","sell":"0","category":"Unite Vehicles","subCategory":"Police","available":true},
        { "name": "Mercedes SLS AMG (Police)",            "id": "49005", "price": "95000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Police", "available": true },
        { "name": "Mercedes SLS AMG (Undercover)",        "id": "49024", "price": "100000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Police", "available": true },
        { "name": "Nissan GTR R35 2007 (Police)",         "id": "49002", "price": "145000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Police", "available": true },
        { "name": "Nissan GTR R35 2007 (Undercover)",     "id": "49003", "price": "150000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Police", "available": true },
        { "name": "Nissan Silvia S15 (Police)",           "id": "49025", "price": "40000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Police", "available": true },
        { "name": "Nissan Silvia S15 (Undercover)",       "id": "49026", "price": "45000",  "sell": "0", "category": "Unite Vehicles", "subCategory": "Police", "available": true },
        { "name": "Saleen S7 TT (Police)",                "id": "49027", "price": "200000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Police", "available": true },
        { "name": "Saleen S7 TT (Undercover)",            "id": "49028", "price": "205000", "sell": "0", "category": "Unite Vehicles", "subCategory": "Police", "available": true },

        /* ── Vanilla Vehicles Legacy ── Civilian ── */
        { "name": "Austin Martin Vantage",           "id": "39100", "price": "70000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Aw-D RS E-Tron",                  "id": "39090", "price": "42000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Bendlee Continental",              "id": "39660", "price": "70000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Cavallo Testarrosa",               "id": "39620", "price": "55000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "DeLauren Alpha 5",                 "id": "39080", "price": "48000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Doge Challenger",                  "id": "39150", "price": "62000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Doge Challenger Whistlin Diesel",  "id": "39500", "price": "66666",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Doge Charger",                     "id": "39010", "price": "22000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Folkswagon Golf",                  "id": "39730", "price": "23000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Hors Crown",                       "id": "39030", "price": "17000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Hors E-350",                       "id": "39180", "price": "17000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Hors Explorer",                    "id": "39040", "price": "19000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Hors F-150",                       "id": "39720", "price": "30000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Hors F-100",                       "id": "39570", "price": "18000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Hors GT40",                        "id": "39070", "price": "100000", "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Hors GT40 W-ART",                  "id": "39310", "price": "130000", "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Hors Puma",                        "id": "39650", "price": "20000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Hyunight N69",                     "id": "39690", "price": "26000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Hyunight N74",                     "id": "39120", "price": "95000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "KASIN Sentry",                     "id": "39630", "price": "50000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Lamborgine Countach",              "id": "39060", "price": "185000", "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Lamborgine Huracan",               "id": "39230", "price": "80000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Lamborgine Huracan W-ART",         "id": "39270", "price": "250000", "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Mclarry 720s",                     "id": "39640", "price": "80000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Mclarry Senna",                    "id": "39020", "price": "120000", "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Mern Sprinter",                    "id": "39140", "price": "25000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Nikola Model 3",                   "id": "39160", "price": "26000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Pioneer Two",                      "id": "39750", "price": "60000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Ranch Rider Sport",                "id": "39560", "price": "50000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Rimacci Divo",                     "id": "39350", "price": "249999", "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Rizz R1S",                         "id": "39390", "price": "32000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Rizz R1T",                         "id": "39610", "price": "34000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Shimitsubi 3000GT",                "id": "39200", "price": "38000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Shimitsubi 3000GT W-ART",          "id": "39290", "price": "76000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Shimitsubi Evolution XVIII",        "id": "39210", "price": "35000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Shimitsubi Evolution XVIII W-ART",  "id": "39260", "price": "50000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Shimitsubi Montero",               "id": "39520", "price": "26000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Soda Superb",                      "id": "39680", "price": "21000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Tyoda Celica",                     "id": "39320", "price": "22000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Tyoda Celica W-ART",               "id": "39670", "price": "46000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Viechy Corvette",                  "id": "39220", "price": "62000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Viechy Corvette W-ART",            "id": "39250", "price": "160000", "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Viechy El Camino",                 "id": "39330", "price": "25000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Viechy Moov",                      "id": "39530", "price": "25000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Viechy Silverado HD",              "id": "39710", "price": "30000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Viechy Silverado HD Dually",       "id": "39760", "price": "33000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Viechy Silverado HD Triplly",      "id": "39770", "price": "66000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Viechy Tahoe",                     "id": "39190", "price": "19000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "WMB 316i",                         "id": "39510", "price": "19000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "WMB 316i W-ART",                   "id": "39540", "price": "52000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "WMB Z4",                           "id": "39050", "price": "55000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Yeet Willys",                      "id": "39700", "price": "18000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },
        { "name": "Yeet Wrangler",                    "id": "39130", "price": "19000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Civilian", "available": true },

        /* ── Vanilla Vehicles Legacy ── Police ── */
        { "name": "Police Doge Charger",               "id": "39018", "price": "27000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Police", "available": true },
        { "name": "Police Doge Challenger",            "id": "39158", "price": "67000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Police", "available": true },
        { "name": "Police Hors Crown",                 "id": "39038", "price": "22000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Police", "available": true },
        { "name": "Police Hors Explorer",              "id": "39048", "price": "24000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Police", "available": true },
        { "name": "Police KASIN Sentry",               "id": "39638", "price": "55000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Police", "available": true },
        { "name": "Police Lamborgine Countach",        "id": "39068", "price": "190000", "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Police", "available": true },
        { "name": "Police Lamborgine Huracan W-ART",   "id": "39278", "price": "255000", "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Police", "available": true },
        { "name": "Police Mclarry Senna",              "id": "39028", "price": "125000", "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Police", "available": true },
        { "name": "Police Nikola Model 3 (Black)",     "id": "39168", "price": "31000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Police", "available": true },
        { "name": "Police Nikola Model 3 (White)",     "id": "39169", "price": "31000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Police", "available": true },
        { "name": "Police Viechy Tahoe",               "id": "39198", "price": "24000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Police", "available": true },
        { "name": "Police Viechy Corvette",            "id": "39258", "price": "67000",  "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Police", "available": true },

        /* ── Vanilla Vehicles Legacy ── Heavy ── */
        { "name": "National 4400 BT", "id": "39590", "price": "60000", "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Heavy", "available": true },
        { "name": "National 4400 FB", "id": "39580", "price": "60000", "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Heavy", "available": true },

        /* ── Vanilla Vehicles Legacy ── Helicopters ── */
        { "name": "Dorphine AS365", "id": "39300", "price": "60000", "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Helicopters", "available": true },
        { "name": "Skybus AS365",   "id": "39370", "price": "55000", "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Helicopters", "available": true },

        /* ── Vanilla Vehicles Legacy ── Planes ── */
        { "name": "Nessna 182",          "id": "39110", "price": "35000", "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Planes", "available": true },
        { "name": "Crop Duster Nessna 182","id":"39118", "price": "38000", "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Planes", "available": true },
        { "name": "Sea Plane Nessna 182", "id": "39380", "price": "40000", "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Planes", "available": true },
        { "name": "Rrusci SR22T",         "id": "39360", "price": "40000", "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Planes", "available": true },
        { "name": "Racing Rrusci SR22T",  "id": "39368", "price": "42000", "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Planes", "available": true },

        /* ── Vanilla Vehicles Legacy ── Boat ── */
        { "name": "Hydrojet", "id": "39240", "price": "25000", "sell": "0", "category": "Vanilla Vehicles Legacy", "subCategory": "Boat", "available": true }

      ]
    },
    {
      "id": "minecraft",
      "name": "Minecraft",
      "icon": "fa-solid fa-cube",
      "categories": ["All Items"],
      "vehicleCategories": [],
      "items": []
    },
    {
      "id": "rust",
      "name": "Rust",
      "icon": "fa-solid fa-shield-halved",
      "categories": ["All Items"],
      "vehicleCategories": [],
      "items": []
    }
  ]
};